\newpage

# Chapter 4: Climate constrains the current distribution of a highly invasive succulent 

Sam C. Levin $^{\ast1,2,3}$, Roberto Salguero-Gómez $^{3\ddagger}$, Tiffany M. Knight $^{1,2,4\ddagger}$

$^1$Institute of Biology, Martin Luther University Halle-Wittenberg, Am Kirchtor 1, 06108 Halle (Saale), Germany

$^2$German Centre for Integrative Biodiversity Research (iDiv) Halle-Jena-Leipzig, Deutscher Platz 5e, 04103 Leipzig, Germany

$^3$Department of Zoology, 11a Mansfield Rd, University of Oxford, Oxford, OX1 3SZ, UK

$^4$Department of Community Ecology, Helmholtz Centre for Environmental Research-UFZ, Theodor-Lieser-Straße 4, 06120, Halle (Saale), Germany

$^\ddagger$ Joint senior authors


### Abstract



### Introduction

Invasive species are ecological and economic pest at local, regional, and global scales (Pimentel et al. 2005, Vila et al. 2011, Levin et al. 2020). There is an extensive body of work devoted to understanding how invasive species become invasive to begin with (reviewed in Lowry et al. 2013 and Jeschke & Heger 2018). However, generalization across families, genera, and even species remains difficult as environmental contexts can vary greatly across the invaded range, and population level processes (e.g. founder effects, rapid evolution, or hybridization) can induce rapid change in the invading population (XXXX). The former is receiving increasing attention, as there is growing recognition that climate change may interact with these invasions to produce an even greater threat to ecosystems.

Climate change poses an additional challenge for conservation practitioners, both in its own right by altering environmental contexts for endangered species (XXXX) and by facilitating new invasions (XXXX). There is a growing body of literature illustrating the importance of the interaction between climate change and invasions. However, results are appear idiosyncratic beyond the most general of conclusions (e.g. climate change exacerbates some invasions, hinders others). As a result, there are still large gaps in our knowledge with respect to threatened types of biomes, their invaders, and the the impacts said invaders may have in the both the short- and long-term futures. 

Mediterranean biomes are threatened by both climate change (XXXX) and invasions (XXXX). They are home to vast array of endemic plant and animal species, with some nature reserves in Western Cape, South Africa containing more species than the entirety of the UK (XXXX). Outside of South Africa, they are threatened by the _Carpobrotus_ genus (Aizoaceae), particularly _C. edulis_, _C. acinaciformis_, _C. chilensis_, and their hybrids. These species are spreading, mat forming succulents, and are exceptionally competitive for water and light (D'Antonio 199X, Novoa et al. 2012, Campoy et al. 2018). There is a growing body of evidence indicating these species are allelopathic, with their dessicated litter acidifying the soil and preventing other species from germinating (Novoa et al. 2012, Novoa et al. 2014).


Ways we've tried to understand this before

How this paper addresses them

### Methods

This study was conducted across XXX sites spread across South Africa (native range), New Zealand (invaded), Portugal (invaded), and Israel (invaded). Sites in the Northern Hemisphere were sampled in sites in the Northern Hemisphere were sampled in March/April, and sites in the Southern Hemisphere were sampled in September/October each year so that plants were observed during their peak flowering period. Each site was selected based on degree of invasion, and the ability to sample without disturbing local flora and fauna. 

We used drones to collect aerial imagery each population. The following methods are general - site specific modifications to this protocol are described in Table 1 and the ESM. We developed flight plans to map each population using DJI Ground Station Pro v2 (SZ DJI Technology Co.) for iPad (Apple Inc). We used the app to draw polygons over an area of interest, and then let the app compute the optimal flight path given our desired resolution. We selected a flight path that generated a resolution of 0.2 - 0.45 cm/pixel. This resulted in a range of 70-85% side  and front photo overlap. The average width of open flowers is 7.46 cm (+/- 0.008 S.E.) and unripe fruits was 2.32 cm (+/- 0.002 S.E.) across all populations (SC Levin, unpublished data), so this resolution is sufficient to allow us to mark the majority of both in the resulting maps (orthomosaics, see below for more details). Transects were flown with a DJI Phantom 4 Pro v1 (SZ DJI Technology Co.) along the lines of the flight plan generated by DJI GSP and images were recorded at 1.8 - 2m intervals. When batteries reached a critical level of power (i.e. ~20%), we landed the drone, switched the batteries out, and the flight was resumed from the last stopping point. 

Once all images were captured after the first aerial survey, individual photos were processed into a single composite, georeferenced orthomosaic map using Pix4Dmapper (Pix4D SA, 2019). We drew individual polygons around contiguous *Carpobrotus* ramets, assigned each a unique ID number, and counted flowers using a point layer in QGIS (QGIS Development Team 2021). We repeated the process in 2019 by overlaying the 2019 map on the 2018 map and marking polygons for all surviving individuals as well as new recruits also in QGIS. Individual ramets that were not found again in our second aerial survey were assumed dead. Maps were aligned between the first and second surveys using the Georeferencer GDAL plugin (QGIS Development Team 2021) in QGIS because the georeferencing of the orthomosaics was only accurate to ~5m. This plugin allows users to manually find and mark common points on both images and set them as reference points for transformation between the old coordinate system (map coordinates of survey 2) and the new coordinate system (map coordinates of survey 1). We used the thin plate splines transformation for the coordinate systems and nearest neighbor resampling method. The reference points are available in the supplementary materials. In addition to drawing polygons around the individual plants, we drew polygons around targets of known sizes and computed the ratio of calculated areas under the polygon vs the known sizes. We then re-scaled all computed sizes of plants using this ratio (Table 1). Once all sizes, flowering information, and survival data were digitized, we used the `sf` and `dplyr` _R_ packages to join all the ramet data into a single dataset. 

```{r echo = FALSE, message = FALSE}
library(tools)

sites <- read.csv("Data/drone_flight_metadata.csv",
                  stringsAsFactors = FALSE) %>%
  filter(population %in% c("Struisbaai", "St_Francis", "Melkboss", "Vogelgat",
                           "Rooisand", "Springfontein", "Rough_Island",
                          "Rarangi", "Foxton", "Whirinaki", "Havatselet",
                           "Praia_de_Areao", "Colares"))

sites$population <- gsub("_", " ", sites$population)

names(sites) <- gsub("_", " ", names(sites))

names(sites) <- toTitleCase(names(sites))

cap <- "Table 4.1: Drone flight dates and conditions"

kable(sites,
       format = "latex",
      # col.names = c("Concept", "Column Name", "Description"),
      caption = cap) %>%
  column_spec(1, border_left = TRUE) %>%
  column_spec(11, border_right = TRUE)

```

The primary goal of this study was to understand how environmental variation constrains or enables _Carpobrotus_ species. Therefore, we compiled a dataset of georeferenced _Carpobrotus_ records from across the globe from GBIF, and cleaned them with the `CoordinateCleaner` _R_ package (Zizka et al. 2019). We downloaded monthly ERA5 climate data from 2018 - 2020 for temperature ($\theta_t$), precipitation ($\theta_p$), and soil water content ($\theta_{s,i}$ where $i$ is the soil layer with values 1-3. See Appendix for more details). Data were kriged for each occurrence point, plus our site coordinates using the `krigR` _R_ package. We aggregated data at both the annual level, and by wet and dry season (i.e. $\theta_s$ for the whole year, one value for the wet season, and one value for the dry season). Finally, we computed how many standard deviations each of our sites was from the global mean value of each environmental covariate to create a standardized environmental value for each site in our data set (Compagnoni et al. 2021).  

We modeled size-dependent survival (Bernoulli model with logit link, $s_a(z, \theta)$), size  at time $t + 1$ ($z'$) conditional on survival and size at time $t$ (Gaussian model with identity link and size dependent variance, $G(z'|z, \sigma, \theta)$), size-dependent probability of flowering (Bernoulli model with logit link, $p_f(z, \theta)$), and size-dependent flower production (negative binomial model with log link, $r_f(z, \theta)$). In addition to size, we included environmental covariates ($\theta$, described in previous paragraph). We constructed Bayesian generalized linear mixed models (GLMMs), and generalized additive mixed models (GAMMs) for each vital rate, and compared models using WAIC, posterior predictive checks, and visual inspection of predictions against the observed data. We selected the best models chosen by WAIC that also made realistic predictions as determined by the latter graphical checks. Each of the potential forms used $\theta_t, \theta_p$ and one of the $\theta_{s,i}$ values as predictors, and interactions between size and environmental covariates were tested as well (included in the GAMMs as tensor product interactions). Because the responses of $p_f(z, \theta)$ and $r_f(z, \theta)$ are based on state at time $t$, we included environmental covariates from the year before the initial demographic sampling (i.e. $t-1$ to $t$), whereas $s_a(z, \theta)$ and $G(z'|z, \sigma, \theta)$ to $t+1$ used environmental data from the year between demographic samples. All candidate models included a population-specific intercept term. All vital rate models were implemented with the `brms` _R_ package (Bürkner et al. 2018).

In addition to the vital rates above, we also modeled the size of new recruits at time $t + 1$ ($r_a(z')$), and estimated probabilities for flower pod survival ($p_{fv}$) and maturation ($p_m$) to time $t+1$, immediate seed germination ($g_i$), total viability ($v_s$), and seed establishment probability ($p_e$), and seed bank germination ($g_{sb}$) and survival ($s_{sb}$).  Data for $r_a(z')$ was collected from the Rooisand site in South Africa. In 2018, we delineated 2 $40 cm \times 40 cm$ plots and counted the number of seedlings. In 2019, we returned and flew brief surveys with the drone at ~ 1.2m above ground level. We generated orthomosaics using the same procedure described above, and then counted surviving seedlings and drew polygons around them to estimate their size. Unfortunately, we did not find seedlings in sufficient quantities at other sites to establish plots, and so our sample size is limited to these two plots for these parameters. We conducted literature reviews to gather estimates of other seed-related parameters, and these were estimated by averaging over the reported estimates (Table XXX).

We used the parameters and functions described above to generate an Integral Projection Model (IPM) for each site.  Our IPM included 1 continuous trait, size ($z, z'$), and 3 discrete states - mature fruits ($mf$), seedlings ($sdl$), and seeds in the seed bank ($sb$) (see Appendix 7 for complete equations and parameter distributions describing the IPM). We combined the vital rate functions described above into an IPM in _R_ using the `ipmr` package (Levin et al. 2021). Point estimates of the deterministic per-capita growth rate for each site, $\lambda_i$ were computed from IPMs parameterized with mean values of the posterior distribution for each parameter estimated in the Bayesian regression models described above. In addition to computing these point estimates, we propagated uncertainty in underlying parameter estimates into the IPM by constructing an IPM from each post-warmup posterior sample, yielding 4000 $\lambda_i$ values. 

LTRE analysis(?)

### Results


### Discussion



### Citations

2. Bürkner, P.-C. (2018). Advanced Bayesian Multilevel Modeling with the R Package brms. The R Journal, 10(1), 395-411. doi:10.32614/RJ-2018-017

1. Pebesma, E., 2018. Simple Features for R: Standardized Support for Spatial Vector Data. The R Journal 10 (1), 439-446, https://doi.org/10.32614/RJ-2018-009

3. Wickham, H., François, R.,  Henry, L., & Müller, K. (2021). dplyr: A Grammar of Data
  Manipulation. R package version 1.0.7. https://CRAN.R-project.org/package=dplyr

2. Zizka, A., Silvestro, D., Andermann, T., Azevedo, J., Duarte Ritter, C., Edler, D., _et al._ (2019). “CoordinateCleaner: standardized cleaning of occurrence records from biological collection databases.” Methods in Ecology and Evolution 10. DOI: 10.1111/2041-210X.13152 (URL: https://doi.org/10.1111/2041-210X.13152), R package version 2.0-20

