\newpage
# Synthesis

There is a long history in plant and animal demography of considering demographic responses across relatively small spatial and temporal grains, and a current need to expand this understanding to broader scales (Crone et al. 2010, Roemer et al. 2021). Macroecologists consider how climate influences the distribution and abundance of species, and use models to predict how these patterns may change with climate change. However, demographic studies that focus on vital rates (survival, growth, fecundity) provide a mechanistic understanding for how species respond to climate (e.g. Compagnoni et al. 2021). Studying demography at macroecological scales can provide a better understanding of how different populations are responding to climate, and what drivers are most important for their vital rates and persistence.

Moving towards broader spatial scales in demography has been limited by having appropriate tools for synthesis and rapid demographic data collection. This dissertation aims to fill these gaps and study populations of the same species that occur across different continents. I develop and apply new tools that can help researchers address questions related to demography and population dynamics across various temporal and spatial scales, and applies them to a focal genus to understand how climate affects the population dynamics of a problematic invasive plant species. The computational framework introduced in chapter 2,  `ipmr`, is both a standalone tool for creating Integral Projection Models (IPMs) of any population (Chapter 4, Bogdan et al. 2021) and is an underlying engine for synthesis work (Chapter 3). In Chapter 3, I demonstrate how to use `ipmr` and `Rpadrino` to implement many IPMs across many spatial scales, and the supplementary materials provide a framework for addressing the relationship between range centrality and species fitness, demonstrating their use for macro-ecological applications. In chapter 4, I use a novel data collection techniques (unmanned aerial vehicles) and `ipmr` to study the demographic responses of an invasive succulent plant species across multiple continents that span its native and exotic ranges. I show that climate does not constrain the fitness of this plant species as hypothesized, suggesting that other factors may mediate its ability to colonize and thrive.

### Advances in standalone IPMs

Integral projection models have become a popular tool for researchers across many disciplines to model population performance, evolutionary and life history trajectories, and species fitness in continuously structured populations (Ellner, Childs, & Rees 2016). Following their introduction in 2000 (Easterling, Ellner & Dixon 2000), researchers have developed increasingly complex IPMs to capture the nuanced responses to drivers such as climate (e.g. Hindle et al. 2018), competition (Adler et al. 2010), and changes in continuous structure within discrete groups (e.g. two sex models, Erickson et al. 2017). In parallel with these theoretical and applied developments, researchers created computational tools that help create and analyze IPMs (Metcalf et al. 2013, Shefferson et al. 2020). Despite the uptick in the popularity of IPMs, computational tools to implement IPMs have not kept pace with development of theory.

In chapter 2, I introduced the _R_ package, `ipmr`. `ipmr` provides a miniature domain specific language to implement a wide range of IPMs. `ipmr` provides functionality for basic analyses, and extensive documentation to aid researchers in implementing more complex analyses (Appendix 1 & Appendix 2). At present, it can handle both simple and general IPMs (_sensu_ Ellner & Rees 2006), deterministic and two types of stochastic models (Rees & Ellner 2009), and density/frequency-independent or -dependent models. Furthermore, `ipmr` handles two-sex models (W. Petry, personal communication), and nested combinations of continuous traits within discrete trait models (e.g. Ellner, Childs & Rees 2016, Chapter 6, Metcalf et al. 2009), which were either exceptionally difficult or impossible to implement with previously written _R_ packages. 

`ipmr` provides a syntax that mimics the mathematical notation of IPMs, and it does not attempt to abstract over the vital rate modeling step of IPM construction. These two features provide a number of advantages over prior work. First, these two features enable researchers to use any functional form they desire to specify the relationship between a trait value and a vital rate. These two features enable researchers to leverage new developments in regression modeling as they become available, rather than having to wait for `ipmr`'s maintainers to implement a way of integrating them into the package. As long as a researcher can write out the functional form of the response (or the regression technique includes a `predict()` method), then it is available for use in `ipmr`. Second, there is no limit on the number of vital rates, structuring traits, and there are no rules on how these may relate to each other (though, in practice, having too many of either may result in painfully slow performance - the curse of dimensionality spares no one). This feature enables researchers to model populations of increasing complexity without having to think too hard about model implementation - the researcher can keep adding new sub-kernels to the IPM and `ipmr` will implement them. One final implication of decoupling vital rate modelling from IPM implementation is that raw data are not required to implement an IPM with `ipmr`. One can assume functional forms for different vital rates, work out reasonable ranges for parameter values, and then simulate populations. Prior to this development, researchers who wished to use an _R_ package to implement their IPM would have to simulate data, fit regression models to that data, and then construct an IPM. This feature also enables PADRINO (introduced in chapter 3) to drastically reduce the amount of data it has to store to reconstruct published IPMs.

### Summary of new features for synthesis

Another key piece of `ipmr`'s functionality that sets it apart from prior work is the `proto_ipm` data structure. This data structure provides a unified way of describing every IPM that one can implement with `ipmr`, and so is a common form that can be shared by both user-defined IPMs and ones defined by PADRINO, which is introduced in chapter 3. The `proto_ipm` is essentially a data frame that houses the symbolic definition of the sub-kernels, the parameters associated with this definition, and then the numerical details that implement the model (e.g. domain limits for continuous traits, integration rules, etc.). This means that once a user defines one or more `proto_ipm`s using their own data and/or data from PADRINO, a single set of computational machinery can be applied to implement their models, drastically reducing the amount of time required to conduct multi-model synthesis work. 

PADRINO provides a database that stores peer-reviewed, published IPMs. `Rpadrino` leverages the aforementioned features of `ipmr` to reconstruct them for users. Specifically, PADRINO stores the mathematical form of published IPMs as text strings and `Rpadrino` makes use of _R_'s ability to parse text into code as well as modify code's evaluation environments to ensure that IPMs are reconstructed as published. `Rpadrino` breaks this down into two steps: re-generating `proto_ipm`s from PADRINO's symbolic model definitions, and then generating actual IPM objects. This segmenting of the steps enables users to combine their own IPMs with database-generated ones. Furthermore, the consistent structure of the outputs makes programming complex synthesis more straightforward, as there is type-consistency in the outputs.

In Appendix 4 of Chapter 3, I show how to use these larger data sets for synthetic work. Specifically, I use a single interface for implementing multiple models by re-constructing IPMs for 23 species and then computing sensitivities and elasticities of population growth rate, as well as mean lifetime recruit production. This appendix further demonstrates the advantages of using an expression based framework by demonstrating how to alter vital rate functions and compute function value perturbations. For example, I provide a case study for how to correct unrealistic functions in an IPM. This functionality allows users to make more complete use of the data stored in the database by correcting issues with published IPMs that would otherwise be unusable for a particular analysis. The combination of `Rpadrino` and PADRINO also provides a framework for theoreticians to experiment with the consequences of altering the relationships between traits and vital rates using realistic demographic information. 

Appendix 5 of Chapter 3 demonstrates another important result for researchers interested in synthesis. This appendix combines data from user-defined models as well as other open access databases to informally address a long-standing question in ecology. This appendix leverages range maps from BIEN (Maitner _et al._ 2017) and COMPADRE (Salguero-Gomez _et al._ 2014) to estimate the relationship between range centrality and population growth rate ($\lambda$). In doing so, I provide a code template that can be repurposed by other researchers to clean and filter publicaly accessible data and conduct larger scale syntheses than were previously possible.

### Applications

Thus far, I have detailed only of what might be done with the novel tools I have developed, rather than what has been done with them. `ipmr` has been used to construct a simple model for a population of _Carpobrotus_ species in Israel (Bogdan et al. 2020), examine the effects of harvesting and fire on three economically important tree species in the Western Ghats of India (Neeraja _et al._ 2022), explore the role of climate change on perennial grasslands (Andrzejak et al. 2023), and to construct an age and size structured model of the impacts of temperature on the invasive Asian Carp (Brook 2021). 

In chapter 4, I use `ipmr` to generate an IPM that examines population performance at the local scale and species performance at a macro-ecological scale to investigate how climate affects the *Carpobrotus* genus across its native and invaded range. Contrary to my expectations, this work revealed that climate is not very important in determining the success of this invasive genus. There are a myriad of reasons why this may be the case, ranging from the statistical limitations (_i.e._ a lack of power) to the biological drivers (_e.g._ biotic interactions are more important and mask the relatively smaller climate effects). Climate's lack of importance in explaining $\lambda$ reveals the importance of both temporal and spatial scale in studies like this. Regarding the former, single years are often not sufficient to capture a relationship between climate variables and population performance, due to, for example, single year deviations from longer-term weather patterns may confound signal (Compagnoni et al. 2023). Regarding biological explanations, populations may experience different biotic interactions, and genetic bottlenecks that are imposed on a species via introduction to a new region (founder effects and subsequent adaptation).

It has been suggested that space might be substituted for time when studying various facets of biodiversity and population biology (Blois et al. 2013, but see Dammand 2019). As such, sampling multiple populations that experience different climates in a single year might provide insight into how a single population would respond to climate changes that occur across longer time scales. However, I found that sampling 13 populations spread across 4 continents was not sufficient to detect climate effects on demography. I argue that a more successful approach, in hindsight, would have been to increase replication within each climate band, rather than sampling populations that span across a broad climate gradient. This alternative approach would have allowed me to disentangle the within-band, across site variation on one hand, and the variation arising across climate bands on the other hand (Compagnoni et al. 2022).

### Limitations of these new frameworks

In addition to the limitations of the space for time substitutions, which are discussed in chapter 4 and in the preceding paragraph, there are other limitations to this dissertation's research. The _R_ packages `ipmr` and `Rpadrino`, and the PADRINO database, for all of their flexibility, are not capable of implementing all possible IPMs. For example, `ipmr` is not able to accommodate time-lagged models (i.e. historical IPMs _sensu_ Shefferson _et al._ 2020) or periodic models (Letcher _et al._ 2014). Despite `ipmr`'s ability to handle semi- and non-parametric models for vital rates, a general syntax for describing them in PADRINO has not yet been developed either. Thus, IPMs that include, for example, generalized additive models (Wood 2017) are not yet available for synthesis. Another, more general, limitation of PADRINO is that the data contained therein may not be biologically correct - the only criteria for inclusion in that database is that the model has received some sort of peer review (i.e. are either published in a peer reviewed journal, are part of an MSc. or PhD thesis, or a technical report). Therefore, the models may be all biologically unrealistic, even if they have passed peer review. For an example of how this limitation looks in practice (and how to overcome it provided it is recognized by the user), see Appendix 4 of Chapter 3.

### Future directions for research

Ecology faces the challenge of scaling our understanding of ecological systems across different spatial and temporal grains. To tackle this challenge, ecologists must develop methods and frameworks for integrating data and observations across scales. This dissertation contributes to advancing ecology by filling key gaps in our ability to study demography at broad spatial and temporal scales. There are some key areas that are important to develop along this line in future research. The first recommendation for future research is with regard to chapters 2 and 3. The _R_ packages `ipmr` and `Rpadrino` are promising tools for generating point estimate of demographic quantities. However, quantifying uncertainty is an essential exercise for every scientist, regardless of field. Currently, neither framework provides off the shelf functionality to propagate uncertainty in parameters/vital rates into uncertainty in the demographic quantities of interest. At the moment, an `ipmr` vignette is the only resource provided to users to demonstrate how one might generate a posterior distribution for the population growth rate $\lambda$. This documentation alone is certainly insufficient given that no robust inference can be made without an understanding of how the outcome of interest may vary. This is an important area of future development for both tools to reach their full potential.

The outcome of interest in most studies extends beyond $\lambda$. While `ipmr` contains functionality to calculate deterministic and stochastic eigenvectors, this _R_ package does not contain functionality to calculate many other metrics. The documentation provides some overview of how to compute other metrics, though it is far from exhaustive (see Ellner, Childs, & Rees 2016). This limitation is largely by design, as combining too much into a single piece of software makes it harder to maintain (the principle of conscious decoupling). A third package is needed that contains functionality to conduct more complex analyses on `ipmr` and `Rpadrino` outputs. 

There is an ever growing list of publications that make use of IPMs, and PADRINO will require constant attention to keep it updated. One priority for the digitization team should be to balance out the phylogenetic representation of the database. Currently, it is quite plant-heavy, which reflects my own personal interests but is not reflective of the sampling effort made by the field as whole. Synthesis requires consideration of sample sizes and the balance of each factor under consideration, so it would be ideal to allow users to make full use of data without having to correct for these issues as much as they currently may have to.

Ecologists are aware that large scale drivers may exhibit small effect sizes when studied at finer spatial or temporal grains. Chapter 4 highlights this phenomenon. There are two key next steps for this work. First, to ensure that future sampling adds additional sites that are close to existing ones, rather than attempting to add sites that occupy additional climate space. Second, consider other drivers of invasiveness simultaneously to understand relative importance of these drivers. These two improvements will likely yield far more insight than the broad scale sampling of climate alone discussed in Chapter 4.

### Concluding remarks

The computational framework introduced in chapters 2 and 3 provides a new way for researchers to generate and synthesize demographic data across a variety grains and scales. Their flexibility will hopefully provide researchers with a toolkit to address broader questions with the appropriate methods and statistical power. Despite their limitations, they have already found use in the literature. As they are open source and open access, both using and contributing to them can be a collaborative endeavor.

In practice, devising an appropriate sampling scheme for detecting climate drivers on demographic responses is far more nuanced and challenging than simply sampling far and wide, as I did in Chapter 4. Careful consideration must be given to the spatial and temporal scales of the expected effects in question, and to the level of replication required to detect them. On the other hand, regardless of the presence or absence of a detectable climate effect on fitness, we do know that invasive species are harmful to biodiversity and economic interests. We should not take the absence of an observed climate effect to indicate that a species poses no threat beyond its current distribution, and policy should reflect this existing knowledge. 

### Citations

1. Bogdan, A., Levin, S.C., Salguero-Gomez, R. (2020) Demographic analysis of an Israeli Carpobrotus population. PLoSONE. https://doi.org/10.1371/journal.pone.0250879 

2. Ellner, S.P., Childs, D.Z., Rees, M. (2016) Data-driven modelling of structured populations: a practical guide to the integral projection model. Basel, Switzerland: Springer International Publishing AG

3. Easterling, M.R., Ellner, S.P., & Dixon, P.M. (2000). Size specific sensitivity: applying a new structured population model. Ecology 81(3): 694-708.

4. Ellner, S.P. & Rees, M. (2006). Integral Projection Models for species with complex demography. The American Naturalist 167(3): 410-428.

5. Rees, M., & Ellner, S. P. (2009). Integral projection models for populations in temporally varying environments. Ecological Monographs, 79(4), 575–594. https://doi.org/10.1890/08-1474.1.

6. Maitner, B., Boyle B., Casler N., Condit R., Donoghue J., Duran S.M., et al. (2017) The bien r package:
A tool to access the Botanical Information and Ecology Network (BIEN) database. Methods in Ecology
and Evolution 9(2): 373-379. https://doi.org/10.1111/2041-210X.12861

7. Levin, S.A. (1989). The problem of pattern and scale in ecology. Ecology 73(6): 1943-1967.

8. Erickson, R.A., Eager, E.A., Brey, M.B., Hansen, M.J., & Kocovsky, P.M. (2017). An integral projection model with YY-males and application to evaluating grass carp control. Ecological Modelling 361: 14-25. https://doi.org/10.1016/j.ecolmodel.2017.07.030

9. Metcalf, C. J. E., McMahon, S. M., Salguero-Gómez, R., & Jongejans, E. (2013). IPMpack: An R package for integral projection models. Methods in Ecology and Evolution., 4(2), 195–200. https://doi.org/10.1111/2041-210x.12001

10. Shefferson, R. P., Kurokawa, S., & Ehrlen, J. (2020). LEFKO3: Analysing individual history through size-classified matrix population models. Methods in Ecology and Evolution. https://doi. org/10.1111/2041-210X. 13526

11. Metcalf, C. J. E., Horvitz, C. C., Tuljapurkar, S., & Clark, D. A. (2009). A time to grow and a time to die: a new way to analyze the dynamics of size, light, age, and death of tropical trees. Ecology, 90(10), 2766-2778.

12. Salguero-Gómez, R, Jones, O.R., Archer, C.A., Buckley, Y.M., Che-Castaldo, J., Caswell, C., Hodgson, D., Scheuerlein, A., Conde, D.A., Brinks, E., de Buhr, H., Farack, C., Gottschalk, F., Hartmann, A., Henning, A., Hoppe, G., Roemer, G., Runge, J., Ruoff, T., etal. (2014) The COMPADRE Plant Matrix Database: an online repository for plant population dynamics. Journal of Ecology 103: 202-218. https://doi.org/10.1111/1365-2745.12334

13. Neeraja, U. V., Saneesh, C. S., Dyda, V., Reddy, H., Yadama, G. N., & Knight, T. M. (2022). Harvesting has variable effects on demographic rates and population growth across three dry forest tree species. Biotropica, 54(6), 1376-1389.

14. Brook, M. (2021). Impacts of temperature on Asian Carp life history and population growth (Master's thesis, University of Waterloo).

15. Letcher, B.H., Schueller, P., Bassar, R.D., Nislow, K.H., Coombs, J.A.,Sakrejda, K. et al. (2014). Robust estimates of environmental effects on population vital rates: an integrated capture-recapture model of seasonal brook trout growth, survival and movement in a stream network. Journal of Animal Ecology 84(2): 337-352. https://doi.org/10.1111/1365-2656.12308

16. Wood, S.N. (2017). Generalized Additive Models: An Introduction with R (2nd edition). Chapman and Hall/CRC.

17. Compagnoni, A., Levin, S., Childs, D.Z. et al. Herbaceous perennial plants with short generation time have stronger responses to climate anomalies than those with longer generation time. Nat Commun 12, 1824 (2021). https://doi.org/10.1038/s41467-021-21977-9

18. Hindle, B., Rees, M., Sheppard, A.W., Quintana-Ascensio, P.F., Menges, E.S., & Childs, D.Z. (2018). Exploring population responses to environmental change when there's never enough data: a factor analytic approach. Methods in Ecology and Evolution 9(11): 2283-2293. https://doi.org/10.1111/2041-210X.13085

19. Adler, P.B., Ellner, S.P., & Levine, J.M. (2010). Coexistence of perennial plants: an embarrassment of niches. Ecology Letters 13(8): 1019-1029. https://doi.org/10.1111/j.1461-0248.2010.01496.x

20. Compagnoni, A., Evers, S., & Knight, T.M. (2022). Spatial replication should be prioritized to advance our understanding of population responses to climate. BioRxiv https://doi.org/10.1101/2022.06.24.497542

Crone, E.E., Menges, E.S., Ellis, M.M., Bell, T., _et al._ (2010). How do plant ecologists use matrix population models? Ecology Letters 14(1): 1-8.

Roemer, G., Dahlgren, J.P., Saluero-Gomez, R., Stott, I.M., Jones, O.R. (2023). Plant demographic knowledge is biased towards short-term studies of temperate-region herbaceous perennials. BioRXiv. https://doi.org/10.1101/2021.04.25.441327

Andrzejak, M., Knight, T.M., Plos, C., & Korell, L. (2023). Reproductive success mediates the effects of climate change and grassland management on plant populations dynamics. BioRXiv. https://doi.org/10.1101/2023.04.26.538388

Blois, J.L., Williams, J.W., Fitzpatrick, M.C., Jackson, S.T., & Ferrier, S. (2013). Space can substitute for time in predicting climate-change effects on biodiversity. Proceedings of the National Academy of Sciences 110(23): 9374-9379. https://doi.org/10.1073/pnas.1220228110

Dammand, C. (2019). A Critique of the Space-for-Time Substitution Practice in Community Ecology. Trends in Ecology and Evolution 34(5): 416-421. https://doi.org/10.1016/j.tree.2019.01.013


